pipeline {
    agent any
//        environment {
//        DB_PASSWORD = credentials('DATABASE_PASSWORD')
//    }
    stages {
        stage('Clone') {
            steps {
                git 'https://gitlab.com/qacdevops/chaperootodo_client.git'
            }
        }
        stage('Install Docker') {
            //I'm skipping the deploy docker as I manuall installed it 
            //and it doesn't need to happen on ever build in my environment
            steps {
            echo 'Nothing to Do'
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([string(credentialsId: 'DATABASE_PASSWORD', variable: 'DB_PASSWORD')]) {
                    sh '''docker-compose pull
                    docker-compose up -d'''
                }
            }
        }
    }
}