- hosts: 127.0.0.1
  become: true
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present 
    register: apachevar1
  - name: Make sure a service unit is running and enabled
    systemd:
      state: started
      name: apache2
      enabled: true
  - name: debug message one
    debug:
      msg: "This is a simple message for info"
  - name: debug message two
    debug:
      var: apachevar1.changed
