- hosts: vms
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: true
    - name: Copy the config file
      template:
        src: example-nginx.j2
        dest: /etc/nginx/nginx.conf
      notify: "reload nginx"
    - name: test the webservers
      uri:
        url: "http://localhost"
        
  handlers:    
  - name: "reload nginx"
    systemd:
      name: nginx
      state: reloaded
      enabled: true

