all:
  hosts:     # This is for ungrouped machines
  vars:
    user_name_var: "xif"
#     ansible_ssh_private_key_file: '~/ansible_id_rsa'
  children:  # This means we want our machines in groups
    west:
      hosts:  # this is for the hosts in our group
        172.31.47.18:
          ansible_user: char
    east:
      hosts:
        172.31.38.135:
    vms:
      children: # this is for using our groups as subgroups 
        west:
        east: